/* 默认桌面配置。结构保持为纯 JSON 数据，方便增删快捷方式。 */
window.DEFAULT_DESKTOP_CONFIG = {
  version: 6,
  folders: [],
  searchLabel: "搜索 App、网站或直接上网",
  searchEngine: "google",
  bingWallpaper: null,
  layout: { desktop: {}, tablet: {}, mobile: {} },
  wallpaper: "sunny",
  customWallpaper: "",
  city: { name: "北京", latitude: 39.9, longitude: 116.4 },
  pages: [
    { id: "home", name: "首页", eyebrow: "GOOD DAY, EVERY DAY", title: "今天也要开心呀！" },
    { id: "personal", name: "桌面 2", eyebrow: "YOUR SPACE", title: "慢慢来，也很棒。" },
    { id: "media", name: "桌面 3", eyebrow: "YOUR SPACE", title: "留一点时间给快乐。" },
    { id: "tools", name: "桌面 4", eyebrow: "YOUR SPACE", title: "灵感，现在开始。" }
  ],
  apps: [
    { id: "weboss-settings", system: "settings", name: "设置", icon: "⚙", iconMode: "custom", color: "#78949d", page: "home" },
    { id: "chatgpt", name: "ChatGPT", url: "https://chatgpt.com", icon: "✳", color: "#263f38", page: "home", dock: true },
    { id: "github", name: "GitHub", url: "https://github.com", icon: "GH", color: "#252b3a", page: "home", dock: true },
    { id: "bilibili", name: "B站", url: "https://www.bilibili.com", icon: "▣", color: "#ee8fa7", page: "home", dock: true },
    { id: "google", name: "Google", url: "https://www.google.com", icon: "G", color: "#fbf7ed", page: "home", dock: true },
    { id: "notion", name: "Notion", url: "https://www.notion.so", icon: "N", color: "#f8f7f2", page: "home", dock: true },
    { id: "youtube", name: "YouTube", url: "https://www.youtube.com", icon: "▶", color: "#f16b64", page: "home" },
    { id: "zhihu", name: "知乎", url: "https://www.zhihu.com", icon: "知", color: "#448af0", page: "home" },
    { id: "email", name: "邮箱", url: "https://mail.google.com", icon: "✉", color: "#f8a678", page: "home", dock: true },
    { id: "x", name: "X", url: "https://x.com", icon: "𝕏", color: "#303542", page: "home" },
    { id: "telegram", name: "Telegram", url: "https://web.telegram.org", icon: "➤", color: "#67b2d7", page: "home" },
    { id: "baidu", name: "百度", url: "https://www.baidu.com", icon: "百", color: "#6185e9", page: "home" },
    { id: "douban", name: "豆瓣", url: "https://www.douban.com", icon: "豆", color: "#79aa75", page: "home" },
    { id: "maps", name: "地图", url: "https://www.google.com/maps", icon: "⌖", color: "#83b99f", page: "home" },
    { id: "taobao", name: "淘宝", url: "https://www.taobao.com", icon: "淘", color: "#ef8b62", page: "home" },
    { id: "class", name: "课程平台", url: "https://www.xuetangx.com", icon: "▤", color: "#678ec2", page: "personal" },
    { id: "library", name: "图书馆", url: "https://www.worldcat.org", icon: "▥", color: "#b78859", page: "personal" },
    { id: "drive", name: "网盘", url: "https://drive.google.com", icon: "△", color: "#7aaa8e", page: "personal", dock: true },
    { id: "translate", name: "翻译", url: "https://translate.google.com", icon: "文", color: "#83aadc", page: "personal" },
    { id: "scholar", name: "学术资源", url: "https://scholar.google.com", icon: "✒", color: "#626fb1", page: "personal" },
    { id: "wolfram", name: "公式计算", url: "https://www.wolframalpha.com", icon: "∑", color: "#d97669", page: "personal" },
    { id: "todoapp", name: "ToDo", url: "https://todo.microsoft.com", icon: "✓", color: "#f0bc69", page: "personal" },
    { id: "calendarapp", name: "日历", url: "https://calendar.google.com", icon: "31", color: "#f2f1e8", page: "personal" },
    { id: "mooc", name: "中国大学MOOC", url: "https://www.icourse163.org", icon: "课", color: "#729ac7", page: "personal" },
    { id: "coursera", name: "Coursera", url: "https://www.coursera.org", icon: "C", color: "#5e92d8", page: "personal" },
    { id: "arxiv", name: "arXiv", url: "https://arxiv.org", icon: "aX", color: "#b97772", page: "personal" },
    { id: "wikipedia", name: "维基百科", url: "https://www.wikipedia.org", icon: "W", color: "#6c8187", page: "personal" },
    { id: "deepl", name: "DeepL", url: "https://www.deepl.com/translator", icon: "D", color: "#516c9a", page: "personal" },
    { id: "keep", name: "Google Keep", url: "https://keep.google.com", icon: "✎", color: "#e6b95e", page: "personal" },
    { id: "netflix", name: "Netflix", url: "https://www.netflix.com", icon: "N", color: "#20212c", page: "media" },
    { id: "tencent", name: "腾讯视频", url: "https://v.qq.com", icon: "▶", color: "#57b781", page: "media" },
    { id: "iqiyi", name: "爱奇艺", url: "https://www.iqiyi.com", icon: "iQI", color: "#80b74f", page: "media" },
    { id: "spotify", name: "Spotify", url: "https://open.spotify.com", icon: "♫", color: "#54b575", page: "media" },
    { id: "music", name: "音乐", url: "https://music.163.com", icon: "♫", color: "#e97e7f", page: "media" },
    { id: "steam", name: "游戏", url: "https://store.steampowered.com", icon: "✦", color: "#354b6d", page: "media" },
    { id: "manga", name: "漫画", url: "https://manga.bilibili.com", icon: "漫", color: "#efab96", page: "media" },
    { id: "shopping", name: "购物", url: "https://www.taobao.com", icon: "包", color: "#f68d5c", page: "media" },
    { id: "qqmusic", name: "QQ 音乐", url: "https://y.qq.com", icon: "♫", color: "#7fbd84", page: "media" },
    { id: "twitch", name: "Twitch", url: "https://www.twitch.tv", icon: "▣", color: "#a77bc9", page: "media" },
    { id: "doubanmovie", name: "豆瓣电影", url: "https://movie.douban.com", icon: "映", color: "#78ab89", page: "media" },
    { id: "doubanmusic", name: "豆瓣音乐", url: "https://music.douban.com", icon: "乐", color: "#86ad88", page: "media" },
    { id: "bilibangumi", name: "B站番剧", url: "https://www.bilibili.com/anime", icon: "番", color: "#ea9bb0", page: "media" },
    { id: "epic", name: "Epic Games", url: "https://store.epicgames.com", icon: "E", color: "#3c4b54", page: "media" },
    { id: "vscode", name: "VS Code", url: "https://vscode.dev", icon: "⌘", color: "#408ed4", page: "tools", dock: true },
    { id: "gitlab", name: "GitLab", url: "https://gitlab.com", icon: "◆", color: "#f5a65d", page: "tools" },
    { id: "gitee", name: "Gitee", url: "https://gitee.com", icon: "G", color: "#d65f5e", page: "tools" },
    { id: "gitcode", name: "GitCode", url: "https://gitcode.com", icon: "GC", color: "#586bc2", page: "tools" },
    { id: "cloudflare", name: "Cloudflare", url: "https://dash.cloudflare.com", icon: "☁", color: "#efa965", page: "tools" },
    { id: "figma", name: "Figma", url: "https://www.figma.com", icon: "◧", color: "#bd8dca", page: "tools" },
    { id: "docs", name: "云文档", url: "https://docs.google.com", icon: "▤", color: "#78a9df", page: "tools" },
    { id: "compress", name: "压缩工具", url: "https://squoosh.app", icon: "⇲", color: "#9d83c3", page: "tools" },
    { id: "stackoverflow", name: "Stack Overflow", url: "https://stackoverflow.com", icon: "≡", color: "#e6a063", page: "tools" },
    { id: "mdn", name: "MDN", url: "https://developer.mozilla.org", icon: "M", color: "#4c6578", page: "tools" },
    { id: "codepen", name: "CodePen", url: "https://codepen.io", icon: "⬡", color: "#454b58", page: "tools" },
    { id: "vercel", name: "Vercel", url: "https://vercel.com", icon: "▲", color: "#343945", page: "tools" },
    { id: "unsplash", name: "Unsplash", url: "https://unsplash.com", icon: "▧", color: "#485e67", page: "tools" },
    { id: "tinypng", name: "TinyPNG", url: "https://tinypng.com", icon: "▧", color: "#75af91", page: "tools" }
  ],
  widgets: [
    { id: "clock", type: "clock", page: "home", size: "wide" },
    { id: "weather", type: "weather", page: "home", size: "medium" },
    { id: "calendar", type: "calendar", page: "home", size: "medium" },
    { id: "quote", type: "quote", page: "home", size: "medium" },
    { id: "todo", type: "todo", page: "home", size: "medium" },
    { id: "progress", type: "progress", page: "personal", size: "wide", title: "学习进度", content: "本周已完成 4 / 6 个小目标" },
    { id: "recent", type: "recent", page: "personal", size: "medium" },
    { id: "favorites", type: "favorites", page: "personal", size: "medium" },
    { id: "watching", type: "watching", page: "media", size: "wide" },
    { id: "player", type: "player", page: "media", size: "medium" },
    { id: "note", type: "note", page: "tools", size: "medium", title: "灵感便签", content: "把今天冒出的好点子，先记在这里。" },
    { id: "quick", type: "quick", page: "tools", size: "medium" }
  ],
  todos: [
    { id: "todo-1", text: "完成机械设计作业", done: false },
    { id: "todo-2", text: "去图书馆", done: false },
    { id: "todo-3", text: "健身 1 小时", done: false },
    { id: "todo-4", text: "看一集动漫", done: false }
  ],
  todoDate: "",
  history: [],
  searchHistory: [],
  dock: ["chatgpt", "github", "bilibili", "google", "notion", "email", "drive", "vscode"],
  favoriteIds: ["scholar", "library", "figma"],
  watching: [
    { title: "追一部喜欢的番", subtitle: "动漫 · 继续观看", url: "https://www.bilibili.com/anime/", tone: "peach", mark: "✿" },
    { title: "周末电影清单", subtitle: "电影 · 待观看", url: "https://movie.douban.com", tone: "blue", mark: "◐" },
    { title: "音乐现场", subtitle: "视频 · 收藏", url: "https://www.youtube.com", tone: "lavender", mark: "♫" }
  ]
};
