import {ICON_DESIGN_VERSION,iconDataURL,localIconDesign,recognizableIconDesign,publicSite} from './icon-model.js';
const CACHE_KEY='weboss-icon-cache-v1';
const acceptable=value=>typeof value==='string'&&value.length<20000&&(/^(?:https?:\/\/|data:image\/svg\+xml;charset=utf-8,)/.test(value));
function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image(),timer=setTimeout(()=>{image.src='';reject(Error('icon_timeout'));},2200);image.referrerPolicy='no-referrer';image.onload=()=>{clearTimeout(timer);image.naturalWidth?resolve(src):reject(Error('empty_icon'));};image.onerror=()=>{clearTimeout(timer);reject(Error('icon_failed'));};image.src=src;});}
export class IconStore{
 constructor({storage=globalThis.localStorage,fetcher=(...args)=>fetch(...args),imageLoader=loadImage,now=()=>Date.now()}={}){this.storage=storage;this.fetcher=fetcher;this.imageLoader=imageLoader;this.now=now;this.entries=new Map();this.pending=new Map();this.apiAvailable=true;this.aiAvailable=true;this.aiTail=Promise.resolve();try{for(const [key,value] of JSON.parse(storage?.getItem(CACHE_KEY)||'[]'))if(acceptable(value.src)&&value.expires>now()&&(!['ai','local'].includes(value.source)||value.designVersion===ICON_DESIGN_VERSION))this.entries.set(key,value);}catch{}}
 key(app){return app.iconMode==='custom'?`custom:${app.icon}`:`auto:${new URL(app.url).origin}:${app.name}`;}
 peek(app){return this.entries.get(this.key(app));}
 fallback(app){return {src:iconDataURL(localIconDesign(app)),source:'local',designVersion:ICON_DESIGN_VERSION};}
 remember(key,value){this.entries.set(key,value);while(this.entries.size>400)this.entries.delete(this.entries.keys().next().value);try{this.storage?.setItem(CACHE_KEY,JSON.stringify([...this.entries]));}catch{}return value;}
 async json(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),url==='/api/icon'?45000:10000);try{const response=await this.fetcher(url,{...options,signal:controller.signal});if(response.status===404)this.apiAvailable=false;if(url==='/api/icon'&&response.status===503)this.aiAvailable=false;return await response.json();}catch{return null;}finally{clearTimeout(timer);}}
 resolve(app,{forceAI=false,refresh=false}={}){const key=this.key(app),cached=this.entries.get(key);if(!refresh&&!forceAI&&cached?.expires>this.now())return Promise.resolve(cached);if(this.pending.has(key))return this.pending.get(key);const work=this.find(app,forceAI).then(value=>this.remember(key,value)).finally(()=>this.pending.delete(key));this.pending.set(key,work);return work;}
 async find(app,forceAI){const site=new URL(app.url),manual=app.iconMode==='custom';if(manual){try{return {src:await this.imageLoader(app.icon),source:'custom',expires:this.now()+30*86400000};}catch{return {...this.fallback(app),expires:this.now()+3600000};}}
  if(!forceAI){const tried=new Set(),trySources=async sources=>{for(const src of sources){if(!acceptable(src)||tried.has(src))continue;tried.add(src);try{return {src:await this.imageLoader(src),source:'website',expires:this.now()+7*86400000};}catch{}}return null;};let found=await trySources([`${site.origin}/favicon.ico`]);if(found)return found;
   if(this.apiAvailable&&publicSite(site.origin)){const result=await this.json(`/api/site-icon?site=${encodeURIComponent(site.origin)}`);found=await trySources(result?.candidates||[]);if(found)return found;}
   if(publicSite(site.origin)){found=await trySources([`https://www.google.com/s2/favicons?domain=${encodeURIComponent(site.hostname)}&sz=128`,`https://icons.duckduckgo.com/ip3/${encodeURIComponent(site.hostname)}.ico`]);if(found)return found;}
  }
  if(this.apiAvailable&&this.aiAvailable){const work=this.aiTail.then(()=>this.aiAvailable?this.json('/api/icon',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:app.name.slice(0,64),url:site.origin})}):null);this.aiTail=work.catch(()=>{});const result=await work;if(result?.design){try{const design=recognizableIconDesign(result.design,app);if(design)return {src:iconDataURL(design),source:'ai',designVersion:ICON_DESIGN_VERSION,expires:this.now()+30*86400000};}catch{}}if(result?.error==='rate_limited')return {...this.fallback(app),retry:65000,expires:this.now()+65000};}
  const retry=this.apiAvailable&&this.aiAvailable?65000:0;return {...this.fallback(app),...(retry?{retry}:{}),expires:this.now()+(retry||300000)};
 }
}
