import {bingImageID,normalizeBingImage} from './wallpaper-model.js';
const hosts=['cn.bing.com','www.bing.com'];
const json=(value,status=200)=>Response.json(value,{status,headers:{'Cache-Control':status===200?'public, max-age=1800':'no-store','X-Content-Type-Options':'nosniff'}});
async function limitedText(response){const reader=response.body?.getReader();if(!reader)throw Error('empty');const chunks=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>64000){await reader.cancel();throw Error('large');}chunks.push(value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return new TextDecoder().decode(bytes);}
async function upstream(path,fetcher,image=false){
 for(const host of hosts){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),image?7000:4500);let response;
  try{let target=new URL(path,`https://${host}`);for(let redirects=0;redirects<3;redirects++){response=await fetcher(target.href,{redirect:'manual',signal:controller.signal,headers:{Accept:image?'image/jpeg,image/*;q=0.8':'application/json'},cf:{cacheEverything:true,cacheTtl:image?86400:1800}});if(![301,302,303,307,308].includes(response.status))break;await response.body?.cancel();const location=response.headers.get('Location');if(!location)throw Error('redirect');target=new URL(location,target);if(target.protocol!=='https:'||!hosts.includes(target.hostname)||target.port||target.username||target.password||(image?!bingImageID(target.href):target.pathname!=='/HPImageArchive.aspx'))throw Error('redirect');}
   if(!response?.ok)throw Error('upstream');if(image){if(!/^image\/(?:jpeg|png|webp)(?:;|$)/i.test(response.headers.get('Content-Type')||'')||Number(response.headers.get('Content-Length')||0)>12000000)throw Error('invalid_image');clearTimeout(timer);return response;}
   const type=response.headers.get('Content-Type')||'';if(!/application\/json/i.test(type))throw Error('invalid_metadata');const value=normalizeBingImage(JSON.parse(await limitedText(response)));clearTimeout(timer);return value;
  }catch{controller.abort();await response?.body?.cancel().catch(()=>{});}finally{clearTimeout(timer);}
 }throw Error('bing_unavailable');
}
function limitedImage(response){const reader=response.body.getReader();let size=0,finished=false;const timer=setTimeout(()=>{reader.cancel().catch(()=>{});},20000),finish=()=>{if(!finished){finished=true;clearTimeout(timer);reader.releaseLock();}};return new ReadableStream({async pull(controller){try{const {done,value}=await reader.read();if(done){finish();controller.close();return;}size+=value.byteLength;if(size>12000000){await reader.cancel();throw Error('image_too_large');}controller.enqueue(value);}catch(error){finish();controller.error(error);}},async cancel(){try{await reader.cancel();}finally{finish();}}});}
export async function wallpaperAPI(request,env,{fetcher=fetch}={}){
 const url=new URL(request.url);if(!['GET','HEAD'].includes(request.method))return json({error:'method_not_allowed'},405);
 const image=url.pathname==='/api/wallpaper/bing/image',id=url.searchParams.get('id');if(image&&!bingImageID(`https://cn.bing.com/th?id=${encodeURIComponent(id||'')}`))return json({error:'invalid_image'},400);
 if(!env.WALLPAPER_LIMITER)return json({error:'wallpaper_not_configured'},503);if(!(await env.WALLPAPER_LIMITER.limit({key:request.headers.get('CF-Connecting-IP')||'local'})).success)return json({error:'rate_limited'},429);
 try{if(!image){const data=await upstream('/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-CN',fetcher);const response=json(data);return request.method==='HEAD'?new Response(null,{headers:response.headers}):response;}
  const response=await upstream(`/th?id=${encodeURIComponent(id)}`,fetcher,true),headers={'Content-Type':response.headers.get('Content-Type'),'Cache-Control':'public, max-age=86400, stale-while-revalidate=604800','X-Content-Type-Options':'nosniff'};if(response.headers.has('ETag'))headers.ETag=response.headers.get('ETag');if(request.method==='HEAD'){await response.body?.cancel();return new Response(null,{headers});}if(!response.body)throw Error('empty_image');return new Response(limitedImage(response),{headers});
 }catch{return json({error:'bing_unavailable'},502);}
}
